### ISSUE TITLE
Reversing?

### ISSUE THREAD

**Issue by jsl303** [yu4u/mixup-generator#6]
Is batch_ids[:self.batch_size] and batch_ids[self.batch_size:]  trying to mirror each other?
However, batch_ids[self.batch_size:] should return an empty array.
a = [1,2,3,4,5]
a[:5] -> [1, 2, 3, 4, 5]
a[5:] -> []

**Comment by yu4u** [comment]
```
batch_ids = indexes[i * self.batch_size * 2:(i + 1) * self.batch_size * 2]
```

**Comment by jsl303** [comment]
Ah, .batch_size * 2 makes sense!
